// The recommended reading, grouped by what each shelf is for.
//
// Titles and authors stay in English in both languages, like the product names
// in the stack: these are published works with one name each, and translating
// "Designing Data-Intensive Applications" would send a reader looking for a
// book that does not exist. Only the group labels change language, and those
// live in the dictionary.
const READING = [
  {
    id: 'ai',
    books: [
      { title: 'AI Engineering', author: 'Chip Huyen', icon: 'architecture' },
      { title: 'Build a Large Language Model (From Scratch)', author: 'Sebastian Raschka', icon: 'rag' },
      { title: 'Hands-On Large Language Models', author: 'Jay Alammar & Maarten Grootendorst', icon: 'rag' },
      { title: 'Designing Machine Learning Systems', author: 'Chip Huyen', icon: 'ml' },
      {
        title: 'Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow',
        author: 'Aurélien Géron',
        icon: 'ml',
      },
      { title: 'LLM Engineer’s Handbook', author: 'Paul Iusztin & Maxime Labonne', icon: 'craft' },
      { title: 'Designing Multi-Agent Systems', author: 'Victor Dibia', icon: 'multiAgent' },
      { title: 'Building Applications with AI Agents', author: 'Michael Albada', icon: 'agents' },
      {
        title: 'Natural Language Processing with Transformers',
        author: 'Lewis Tunstall, Leandro von Werra & Thomas Wolf',
        icon: 'rag',
      },
      { title: 'Prompt Engineering for LLMs', author: 'John Berryman & Albert Ziegler', icon: 'prompt' },
      { title: 'Building LLMs for Production', author: 'Louis-François Bouchard & Louie Peters', icon: 'observability' },
      { title: 'AI Agents in Action', author: 'Micheal Lanham', icon: 'agents' },
      { title: 'Prompt Engineering for Generative AI', author: 'James Phoenix & Mike Taylor', icon: 'prompt' },
      { title: 'The Hundred-Page Language Models Book', author: 'Andriy Burkov', icon: 'rag' },
      { title: 'The Hundred-Page Machine Learning Book', author: 'Andriy Burkov', icon: 'ml' },
      { title: 'Deep Learning', author: 'Ian Goodfellow, Yoshua Bengio & Aaron Courville', icon: 'ml' },
      {
        title: 'Why Machines Learn: The Elegant Math Behind Modern AI',
        author: 'Anil Ananthaswamy',
        icon: 'exactSciences',
      },
      { title: 'Co-Intelligence: Living and Working with AI', author: 'Ethan Mollick', icon: 'ethics' },
      {
        title: 'The Alignment Problem: Machine Learning and Human Values',
        author: 'Brian Christian',
        icon: 'ethics',
      },
    ],
  },
  {
    id: 'craft',
    books: [
      { title: 'The Pragmatic Programmer', author: 'Andrew Hunt & David Thomas', icon: 'craft' },
      { title: 'Clean Code', author: 'Robert C. Martin', icon: 'craft' },
      { title: 'Refactoring', author: 'Martin Fowler', icon: 'refactor' },
      { title: 'The Mythical Man-Month', author: 'Frederick P. Brooks Jr.', icon: 'projectPlan' },
      { title: 'Code Complete', author: 'Steve McConnell', icon: 'craft' },
      { title: 'A Philosophy of Software Design', author: 'John Ousterhout', icon: 'architecture' },
      { title: 'Working Effectively with Legacy Code', author: 'Michael Feathers', icon: 'debt' },
      { title: 'Test-Driven Development: By Example', author: 'Kent Beck', icon: 'testTime' },
      { title: 'Tidy First?', author: 'Kent Beck', icon: 'refactor' },
      {
        title: 'Design Patterns',
        author: 'Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides',
        icon: 'architecture',
      },
      { title: 'Growing Object-Oriented Software, Guided by Tests', author: 'Steve Freeman & Nat Pryce', icon: 'bdd' },
      {
        title: 'Structure and Interpretation of Computer Programs',
        author: 'Harold Abelson & Gerald Jay Sussman',
        icon: 'exactSciences',
      },
      {
        title: 'Code: The Hidden Language of Computer Hardware and Software',
        author: 'Charles Petzold',
        icon: 'exactSciences',
      },
      {
        title: 'Introduction to Algorithms',
        author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest & Clifford Stein',
        icon: 'optimization',
      },
      { title: 'Grokking Algorithms', author: 'Aditya Bhargava', icon: 'optimization' },
      { title: 'Programming Pearls', author: 'Jon Bentley', icon: 'craft' },
      { title: 'The Art of Readable Code', author: 'Dustin Boswell & Trevor Foucher', icon: 'craft' },
      { title: 'Software Engineering at Google', author: 'Titus Winters, Tom Manshreck & Hyrum Wright', icon: 'scale' },
      { title: 'Modern Software Engineering', author: 'David Farley', icon: 'experiment' },
    ],
  },
  {
    id: 'systems',
    books: [
      { title: 'Designing Data-Intensive Applications', author: 'Martin Kleppmann', icon: 'distributed' },
      { title: 'Fundamentals of Software Architecture', author: 'Mark Richards & Neal Ford', icon: 'architecture' },
      {
        title: 'Software Architecture: The Hard Parts',
        author: 'Neal Ford, Mark Richards, Pramod Sadalage & Zhamak Dehghani',
        icon: 'tradeoff',
      },
      { title: 'Clean Architecture', author: 'Robert C. Martin', icon: 'architecture' },
      { title: 'Domain-Driven Design', author: 'Eric Evans', icon: 'dataModel' },
      { title: 'Building Microservices', author: 'Sam Newman', icon: 'microservices' },
      {
        title: 'Building Evolutionary Architectures',
        author: 'Neal Ford, Rebecca Parsons & Patrick Kua',
        icon: 'architecture',
      },
      { title: 'Patterns of Enterprise Application Architecture', author: 'Martin Fowler', icon: 'architecture' },
      { title: 'Enterprise Integration Patterns', author: 'Gregor Hohpe & Bobby Woolf', icon: 'integration' },
      { title: 'Designing Distributed Systems', author: 'Brendan Burns', icon: 'distributed' },
      { title: 'Database Internals', author: 'Alex Petrov', icon: 'sql' },
      { title: 'System Design Interview – An Insider’s Guide', author: 'Alex Xu', icon: 'scale' },
      { title: 'Release It!', author: 'Michael T. Nygard', icon: 'resilience' },
      {
        title: 'Site Reliability Engineering',
        author: 'Betsy Beyer, Chris Jones, Jennifer Petoff & Niall Richard Murphy',
        icon: 'observability',
      },
      { title: 'Continuous Delivery', author: 'Jez Humble & David Farley', icon: 'cicd' },
      { title: 'The DevOps Handbook', author: 'Gene Kim, Jez Humble, Patrick Debois & John Willis', icon: 'cicd' },
      { title: 'Accelerate', author: 'Nicole Forsgren, Jez Humble & Gene Kim', icon: 'scale' },
      { title: 'The Phoenix Project', author: 'Gene Kim, Kevin Behr & George Spafford', icon: 'postmortem' },
      { title: 'Thinking in Systems', author: 'Donella H. Meadows', icon: 'causal' },
    ],
  },
  {
    id: 'leadership',
    books: [
      { title: 'Extreme Ownership', author: 'Jocko Willink & Leif Babin', icon: 'ownership' },
      { title: 'High Output Management', author: 'Andrew S. Grove', icon: 'scale' },
      { title: 'The Manager’s Path', author: 'Camille Fournier', icon: 'strategy' },
      {
        title: 'Staff Engineer: Leadership Beyond the Management Track',
        author: 'Will Larson',
        icon: 'endToEnd',
      },
      { title: 'The Hard Thing About Hard Things', author: 'Ben Horowitz', icon: 'entrepreneur' },
      { title: 'Team Topologies', author: 'Matthew Skelton & Manuel Pais', icon: 'crossFunctional' },
      { title: 'An Elegant Puzzle', author: 'Will Larson', icon: 'strategy' },
      { title: 'The Making of a Manager', author: 'Julie Zhuo', icon: 'mentoring' },
      { title: 'Radical Candor', author: 'Kim Scott', icon: 'mentoring' },
      { title: 'The Five Dysfunctions of a Team', author: 'Patrick Lencioni', icon: 'team' },
      { title: 'Peopleware', author: 'Tom DeMarco & Timothy Lister', icon: 'team' },
      { title: 'Turn the Ship Around!', author: 'L. David Marquet', icon: 'ownership' },
      {
        title: 'Crucial Conversations',
        author: 'Kerry Patterson, Joseph Grenny, Ron McMillan & Al Switzler',
        icon: 'crossFunctional',
      },
      { title: 'Multipliers', author: 'Liz Wiseman', icon: 'mentoring' },
      { title: 'The Culture Code', author: 'Daniel Coyle', icon: 'team' },
      { title: 'Drive', author: 'Daniel H. Pink', icon: 'ownership' },
      { title: 'The Effective Executive', author: 'Peter F. Drucker', icon: 'projectPlan' },
      { title: 'Leaders Eat Last', author: 'Simon Sinek', icon: 'team' },
      { title: 'Good to Great', author: 'Jim Collins', icon: 'scale' },
    ],
  },
  {
    id: 'product',
    books: [
      { title: 'The Lean Startup', author: 'Eric Ries', icon: 'experiment' },
      { title: 'Zero to One', author: 'Peter Thiel & Blake Masters', icon: 'entrepreneur' },
      { title: 'The Mom Test', author: 'Rob Fitzpatrick', icon: 'research' },
      { title: 'Inspired', author: 'Marty Cagan', icon: 'prototype' },
      { title: 'Empowered', author: 'Marty Cagan', icon: 'team' },
      { title: 'Continuous Discovery Habits', author: 'Teresa Torres', icon: 'research' },
      { title: 'Escaping the Build Trap', author: 'Melissa Perri', icon: 'strategy' },
      { title: 'Shape Up', author: 'Ryan Singer', icon: 'projectPlan' },
      { title: 'Hooked', author: 'Nir Eyal', icon: 'usability' },
      { title: 'Crossing the Chasm', author: 'Geoffrey A. Moore', icon: 'marketing' },
      { title: 'The Innovator’s Dilemma', author: 'Clayton M. Christensen', icon: 'risk' },
      { title: 'Good Strategy Bad Strategy', author: 'Richard Rumelt', icon: 'strategy' },
      { title: 'Playing to Win', author: 'A.G. Lafley & Roger L. Martin', icon: 'strategy' },
      { title: 'Blue Ocean Strategy', author: 'W. Chan Kim & Renée Mauborgne', icon: 'strategy' },
      { title: 'Measure What Matters', author: 'John Doerr', icon: 'finance' },
      { title: 'Traction', author: 'Gabriel Weinberg & Justin Mares', icon: 'marketing' },
      { title: 'The Cold Start Problem', author: 'Andrew Chen', icon: 'scale' },
      { title: 'Rework', author: 'Jason Fried & David Heinemeier Hansson', icon: 'entrepreneur' },
      { title: 'Obviously Awesome', author: 'April Dunford', icon: 'marketing' },
    ],
  },
  {
    id: 'design',
    books: [
      { title: 'Don’t Make Me Think', author: 'Steve Krug', icon: 'usability' },
      { title: 'The Design of Everyday Things', author: 'Don Norman', icon: 'usability' },
      { title: 'Refactoring UI', author: 'Adam Wathan & Steve Schoger', icon: 'usability' },
      { title: 'The Non-Designer’s Design Book', author: 'Robin Williams', icon: 'usability' },
      {
        title: 'About Face: The Essentials of Interaction Design',
        author: 'Alan Cooper, Robert Reimann, David Cronin & Christopher Noessel',
        icon: 'usability',
      },
      { title: 'The Elements of User Experience', author: 'Jesse James Garrett', icon: 'architecture' },
      { title: 'Laws of UX', author: 'Jon Yablonski', icon: 'systemOne' },
      { title: '100 Things Every Designer Needs to Know About People', author: 'Susan Weinschenk', icon: 'research' },
      { title: 'Designing Interfaces', author: 'Jenifer Tidwell, Charles Brewer & Aynne Valencia', icon: 'prototype' },
      {
        title: 'Universal Principles of Design',
        author: 'William Lidwell, Kritina Holden & Jill Butler',
        icon: 'usability',
      },
      { title: 'Thinking with Type', author: 'Ellen Lupton', icon: 'docs' },
      { title: 'Grid Systems in Graphic Design', author: 'Josef Müller-Brockmann', icon: 'architecture' },
      { title: 'Interaction of Color', author: 'Josef Albers', icon: 'experiment' },
      { title: 'Atomic Design', author: 'Brad Frost', icon: 'architecture' },
      { title: 'Microinteractions', author: 'Dan Saffer', icon: 'usability' },
      { title: 'Inclusive Design Patterns', author: 'Heydon Pickering', icon: 'ethics' },
      { title: 'Just Enough Research', author: 'Erika Hall', icon: 'research' },
      { title: 'Lean UX', author: 'Jeff Gothelf & Josh Seiden', icon: 'experiment' },
      { title: 'Sprint', author: 'Jake Knapp, John Zeratsky & Braden Kowitz', icon: 'prototype' },
    ],
  },
  {
    id: 'security',
    books: [
      {
        title: 'The Web Application Hacker’s Handbook',
        author: 'Dafydd Stuttard & Marcus Pinto',
        icon: 'ethicalHacking',
      },
      { title: 'Hacking: The Art of Exploitation', author: 'Jon Erickson', icon: 'ethicalHacking' },
      { title: 'Penetration Testing', author: 'Georgia Weidman', icon: 'ethicalHacking' },
      { title: 'The Hacker Playbook 3', author: 'Peter Kim', icon: 'ethicalHacking' },
      { title: 'Black Hat Python', author: 'Justin Seitz & Tim Arnold', icon: 'ethicalHacking' },
      { title: 'Linux Basics for Hackers', author: 'OccupyTheWeb', icon: 'ethicalHacking' },
      { title: 'Real-World Bug Hunting', author: 'Peter Yaworski', icon: 'portScan' },
      { title: 'Hacking APIs', author: 'Corey Ball', icon: 'integration' },
      { title: 'The Tangled Web', author: 'Michal Zalewski', icon: 'networking' },
      { title: 'Practical Malware Analysis', author: 'Michael Sikorski & Andrew Honig', icon: 'research' },
      { title: 'Security Engineering', author: 'Ross Anderson', icon: 'secureDesign' },
      { title: 'Threat Modeling: Designing for Security', author: 'Adam Shostack', icon: 'secureDesign' },
      { title: 'Serious Cryptography', author: 'Jean-Philippe Aumasson', icon: 'passwordCrack' },
      { title: 'Applied Cryptography', author: 'Bruce Schneier', icon: 'passwordCrack' },
      { title: 'The Art of Deception', author: 'Kevin D. Mitnick & William L. Simon', icon: 'risk' },
      { title: 'Ghost in the Wires', author: 'Kevin D. Mitnick & William L. Simon', icon: 'ethicalHacking' },
      { title: 'The Cuckoo’s Egg', author: 'Clifford Stoll', icon: 'networking' },
      { title: 'Countdown to Zero Day', author: 'Kim Zetter', icon: 'control' },
      { title: 'Sandworm', author: 'Andy Greenberg', icon: 'cloudSecurity' },
    ],
  },
  {
    id: 'thinking',
    books: [
      { title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', icon: 'systemOne' },
      { title: 'Thinking in Bets', author: 'Annie Duke', icon: 'risk' },
      { title: 'Superforecasting', author: 'Philip E. Tetlock & Dan Gardner', icon: 'radar' },
      { title: 'The Signal and the Noise', author: 'Nate Silver', icon: 'timeSeries' },
      { title: 'The Black Swan', author: 'Nassim Nicholas Taleb', icon: 'risk' },
      { title: 'Antifragile', author: 'Nassim Nicholas Taleb', icon: 'resilience' },
      { title: 'The Scout Mindset', author: 'Julia Galef', icon: 'research' },
      { title: 'Poor Charlie’s Almanack', author: 'Charles T. Munger', icon: 'finance' },
      { title: 'Algorithms to Live By', author: 'Brian Christian & Tom Griffiths', icon: 'optimization' },
      { title: 'Influence', author: 'Robert B. Cialdini', icon: 'marketing' },
      { title: 'Deep Work', author: 'Cal Newport', icon: 'craft' },
      { title: 'Atomic Habits', author: 'James Clear', icon: 'experiment' },
      { title: 'Mindset', author: 'Carol S. Dweck', icon: 'mentoring' },
      { title: 'Range', author: 'David Epstein', icon: 'crossFunctional' },
      { title: 'Make It Stick', author: 'Peter C. Brown, Henry L. Roediger III & Mark A. McDaniel', icon: 'research' },
      { title: 'Ultralearning', author: 'Scott H. Young', icon: 'research' },
      { title: 'The Art of Doing Science and Engineering', author: 'Richard W. Hamming', icon: 'exactSciences' },
      { title: 'Surely You’re Joking, Mr. Feynman!', author: 'Richard P. Feynman', icon: 'exactSciences' },
      { title: 'Gödel, Escher, Bach', author: 'Douglas R. Hofstadter', icon: 'neuralNet' },
    ],
  },
  {
    id: 'science',
    books: [
      { title: 'Cosmos', author: 'Carl Sagan', icon: 'exactSciences' },
      { title: 'A Brief History of Time', author: 'Stephen Hawking', icon: 'exactSciences' },
      { title: 'Astrophysics for People in a Hurry', author: 'Neil deGrasse Tyson', icon: 'exactSciences' },
      { title: 'The First Three Minutes', author: 'Steven Weinberg', icon: 'exactSciences' },
      {
        title: 'The Feynman Lectures on Physics',
        author: 'Richard P. Feynman, Robert B. Leighton & Matthew Sands',
        icon: 'exactSciences',
      },
      { title: 'QED: The Strange Theory of Light and Matter', author: 'Richard P. Feynman', icon: 'quantum' },
      {
        title: 'Quantum Mechanics: The Theoretical Minimum',
        author: 'Leonard Susskind & Art Friedman',
        icon: 'quantum',
      },
      { title: 'Seven Brief Lessons on Physics', author: 'Carlo Rovelli', icon: 'quantum' },
      { title: 'The Elegant Universe', author: 'Brian Greene', icon: 'quantum' },
      { title: 'The Road to Reality', author: 'Roger Penrose', icon: 'exactSciences' },
      { title: 'What Is Mathematics?', author: 'Richard Courant & Herbert Robbins', icon: 'exactSciences' },
      { title: 'Infinite Powers', author: 'Steven Strogatz', icon: 'exactSciences' },
      { title: 'Fermat’s Enigma', author: 'Simon Singh', icon: 'exactSciences' },
      { title: 'Chaos: Making a New Science', author: 'James Gleick', icon: 'causal' },
      { title: 'The Disappearing Spoon', author: 'Sam Kean', icon: 'materials' },
      { title: 'Napoleon’s Buttons', author: 'Penny Le Couteur & Jay Burreson', icon: 'materials' },
      { title: 'What Is Life?', author: 'Erwin Schrödinger', icon: 'protein' },
      { title: 'The Selfish Gene', author: 'Richard Dawkins', icon: 'bioinformatics' },
      { title: 'The Gene: An Intimate History', author: 'Siddhartha Mukherjee', icon: 'bioinformatics' },
    ],
  },
];

export const BOOK_COUNT = READING.reduce((total, group) => total + group.books.length, 0);

export default READING;
